### ISSUE TITLE
NetCDF hangs in nc_create_par with HDF5 1.14.0

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#2434]
**Describe the bug**
A simple NetCDF program hangs in nc_create_par when MPI_Info_set is set to romio_no_indep_rw "true"

**Expected behavior**
The program should not hang.

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash)
 - OS and version
 - Compiler and version
 - Build system (e.g. CMake, Autotools) and version
 - Any configure options you specified
 - MPI library and version (parallel HDF5)

tested HDF5 13.1 (passes), 13.2(hangs), 14.0(hangs) and develop (hangs).
Linux, GCC 11, MPICH 4, Autotools, NetCDF 4.9.1.

**Additional context**

program
-----------------------

```
#include <stdio.h>
#include <mpi.h>
#include <netcdf.h>
#include <netcdf_par.h>

int main(int argc, char* argv[])
{
    int my_rank;
    MPI_Info info;
    int ncid;

    MPI_Init(&argc, &argv);

    MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);

    MPI_Info_create(&info);
    MPI_Info_set(info, "romio_no_indep_rw", "true");

    nc_create_par("test.nc", NC_CLOBBER | NC_MPIIO | NC_NETCDF4, MPI_COMM_WORLD, info, &ncid);

    printf("Before calling nc_close, rank = %d\n", my_rank);
    fflush(stdout);

    nc_close(ncid);

    printf("After calling nc_close, rank = %d\n", my_rank);
    fflush(stdout);

    MPI_Finalize();

    return 0;
}
```

Backtrace:

```
#0  0x00007fe0b9d0e823 in MPIDI_CH3I_Progress () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#1  0x00007fe0b9c7fba3 in MPIR_Wait_state () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#2  0x00007fe0b9c7fc6f in MPIR_Wait_impl () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#3  0x00007fe0b9c40fb4 in MPIC_Wait () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#4  0x00007fe0b9c413e3 in MPIC_Recv () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#5  0x00007fe0b9bc5631 in MPIR_Bcast_intra_binomial () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#6  0x00007fe0b9c25fb5 in MPIR_Bcast_allcomm_auto () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#7  0x00007fe0b9c260e1 in MPIR_Bcast_impl () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#8  0x00007fe0b9ae8f1b in PMPI_Bcast () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#9  0x00007fe0b9dd2223 in ADIOI_Info_check_and_install_enabled () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#10 0x00007fe0b9db13c9 in ADIOI_GEN_SetInfo () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#11 0x00007fe0b9dc32f8 in ADIO_Set_view () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#12 0x00007fe0b9d9cbf3 in PMPI_File_set_view () from /home/brtnfld/packages/mpich-11/lib64/libmpi.so.12
#13 0x0000000000880949 in H5FD__mpio_write_vector (_file=0x271bc80, dxpl_id=<optimized out>, count=1, types=0x271b3f0, addrs=0x26e3de0, sizes=0x26e3c50, bufs=0x271b3d0) at ../../src/H5FDmpio.c:2623
#14 0x00000000005cd33d in H5FD_write_vector (file=0x271bc80, count=1, types=types@entry=0x271b3f0, addrs=0x26e3de0, sizes=0x26e3c50, bufs=0x271b3d0) at ../../src/H5FDint.c:666
#15 0x00000000005aacb3 in H5F_shared_vector_write (f_sh=<optimized out>, count=count@entry=1, types=types@entry=0x271b3f0, addrs=addrs@entry=0x26e3de0, sizes=sizes@entry=0x26e3c50, bufs=bufs@entry=0x271b3d0) at ../../src/H5Fio.c:401
#16 0x00000000008686d4 in H5C__collective_write (f=f@entry=0x271c0f0) at ../../src/H5Cmpio.c:1030
#17 0x000000000086957c in H5C_apply_candidate_list (f=f@entry=0x271c0f0, cache_ptr=cache_ptr@entry=0x7fe0b796b010, num_candidates=2, candidates_list_ptr=0x26e3480, mpi_rank=<optimized out>, mpi_size=<optimized out>) at ../../src/H5Cmpio.c:378
#18 0x0000000000865607 in H5AC__rsp__dist_md_write__flush (f=f@entry=0x271c0f0) at ../../src/H5ACmpio.c:1689
#19 0x00000000008670df in H5AC__run_sync_point (f=f@entry=0x271c0f0, sync_point_op=sync_point_op@entry=1) at ../../src/H5ACmpio.c:2164
#20 0x00000000008671a1 in H5AC__flush_entries (f=f@entry=0x271c0f0) at ../../src/H5ACmpio.c:2306
#21 0x00000000004d27c9 in H5AC_flush (f=f@entry=0x271c0f0) at ../../src/H5AC.c:675
#22 0x00000000005a01eb in H5F__flush_phase2 (f=f@entry=0x271c0f0, closing=closing@entry=false) at ../../src/H5Fint.c:2182
#23 0x00000000005a3239 in H5F__flush (f=f@entry=0x271c0f0) at ../../src/H5Fint.c:2261
#24 0x00000000005ab46d in H5F__flush_mounts_recurse (f=0x271c0f0) at ../../src/H5Fmount.c:536
#25 0x00000000005ac7f0 in H5F_flush_mounts (f=<optimized out>) at ../../src/H5Fmount.c:574
#26 0x000000000083d4c9 in H5VL__native_file_specific (obj=0x271c0f0, args=0x7ffd7f3a91d0, dxpl_id=<optimized out>, req=<optimized out>) at ../../src/H5VLnative_file.c:311
#27 0x0000000000817479 in H5VL__file_specific (obj=obj@entry=0x271c0f0, cls=0x269fa00, args=args@entry=0x7ffd7f3a91d0, dxpl_id=dxpl_id@entry=792633534417207304, req=req@entry=0x0) at ../../src/H5VLcallback.c:4032
#28 0x0000000000824a8c in H5VL_file_specific (vol_obj=<optimized out>, args=args@entry=0x7ffd7f3a91d0, dxpl_id=792633534417207304, req=req@entry=0x0) at ../../src/H5VLcallback.c:4097
#29 0x000000000059117c in H5F__flush_api_common (object_id=object_id@entry=72057594037927936, scope=scope@entry=H5F_SCOPE_GLOBAL, token_ptr=token_ptr@entry=0x0, _vol_obj_ptr=_vol_obj_ptr@entry=0x0) at ../../src/H5F.c:954
#30 0x00000000005942be in H5Fflush (object_id=72057594037927936, scope=H5F_SCOPE_GLOBAL) at ../../src/H5F.c:981
#31 0x0000000000444cc6 in sync_netcdf4_file (h5=0x26db940) at ../../libhdf5/hdf5file.c:174
#32 0x0000000000444fe5 in nc4_close_hdf5_file (h5=0x26db940, abort=0, memio=0x0) at ../../libhdf5/hdf5file.c:304
#33 0x000000000044574a in NC4_close (ncid=65536, params=0x0) at ../../libhdf5/hdf5file.c:633
#34 0x000000000040617d in nc_close (ncid=65536) at ../../libdispatch/dfile.c:1308
#35 0x00000000004059ba in main (argc=1, argv=0x7ffd7f3a9498) at test_netcdf4_hanging.c:24
```

**Comment by roblatham00** [comment]
Looks like my fault:  Jordan already opened https://github.com/pmodels/mpich/issues/6408  just wanted to make sure it was referenced here as well

**Comment by derobins** [comment]
This is a MPICH issue. Closing.
