### ISSUE TITLE
Segfault H5_gen.F90:4989

### ISSUE THREAD

**Issue by rajeeja** [HDFGroup/hdf5#984]
HDF5 version is the current master. 
This code use to work earlier. 

```


At line 4989 of file H5_gen.F90
Fortran runtime error: Index '1' of dimension 1 of array 'buf' above upper bound of 0

Error termination. Backtrace:
#0  0x5ffb58 in __h5_gen_MOD_h5dread_ckind_rank_1
        at /nfs/proj-flash5/hdf5/fortran/src/H5_gen.F90:4989
#1  0x5d6195 in ???
#2  0x5d9649 in ???
#3  0x5e8812 in ???
#4  0x47c51f in ???
#5  0x411a1d in ???
#6  0x40d2c3 in ???
#7  0x406fd1 in ???
#8  0x2b996a9eff44 in ???
#9  0x40700b in ???
#10  0xffffffffffffffff in ???
```

**Comment by brtnfld** [comment]
Is the dims value that you are passing to H5Dread _f zero? You could try the F2003 version of H5Dread_f instead, which does not require the dim array to see if you have the same issue. Did you declare dims type HSIZE_T?

**Comment by rajeeja** [comment]
Changing versions fixed the issue. Closing this
